[package]
name = "evol_regression"
version = "0.1.0"
authors = ["Bence Meszaros <bence.me@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "1.0.2"
rand = "0.6.0"
statrs = "0.11.0"
approx = "0.3.2"

[profile.release]
lto = true
codegen-units = 1
